// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSKZZiby2z6r0kVZ0m_9aozxq0DUU8BuQ',
    appId: '1:299487844774:web:c2859e486cf65b682c9767',
    messagingSenderId: '299487844774',
    projectId: 'finiapp',
    authDomain: 'finiapp.firebaseapp.com',
    storageBucket: 'finiapp.appspot.com',
    measurementId: 'G-5YHEFG9FEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHPBpAYuRWclR6kbp3aD5SNyMdTOYA9yI',
    appId: '1:299487844774:android:354d02eb093315fb2c9767',
    messagingSenderId: '299487844774',
    projectId: 'finiapp',
    storageBucket: 'finiapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWooIwz9kHGu65PWiADW4_8lFUFPrWRgY',
    appId: '1:299487844774:ios:387d8af6e5ebf6422c9767',
    messagingSenderId: '299487844774',
    projectId: 'finiapp',
    storageBucket: 'finiapp.appspot.com',
    iosClientId:
        '299487844774-skea4lfo406mjiglred8ud042pl3a4ss.apps.googleusercontent.com',
    iosBundleId: 'cl.finia.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWooIwz9kHGu65PWiADW4_8lFUFPrWRgY',
    appId: '1:299487844774:ios:387d8af6e5ebf6422c9767',
    messagingSenderId: '299487844774',
    projectId: 'finiapp',
    storageBucket: 'finiapp.appspot.com',
    iosClientId:
        '299487844774-skea4lfo406mjiglred8ud042pl3a4ss.apps.googleusercontent.com',
    iosBundleId: 'cl.finia.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSKZZiby2z6r0kVZ0m_9aozxq0DUU8BuQ',
    appId: '1:299487844774:web:0b75597cfd0e643b2c9767',
    messagingSenderId: '299487844774',
    projectId: 'finiapp',
    authDomain: 'finiapp.firebaseapp.com',
    storageBucket: 'finiapp.appspot.com',
    measurementId: 'G-QRXTZ3T33T',
  );
}
